name: 'StrokkConfig: Publish'

on:
  push:
    tags: [ "*" ]

jobs:
  publish:
    environment: build
    runs-on: ubuntu-latest
    name: Publish to EldoNexus

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execution rights to Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Publish
        run: ./gradlew publish
        env:
          NEXUS_USERNAME: "${{ secrets.NEXUS_USERNAME }}"
          NEXUS_PASSWORD: "${{ secrets.NEXUS_PASSWORD }}"