name: publish

on:
  workflow_dispatch:
  release:
    tags: [ "**" ]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: publish

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: oracle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish to EldoNexus
        run: ./gradlew publish
        env:
          SKIP_TEST: true
